---

- name: Deploy API Consumer
  hosts: api_consumer
  user: ubuntu
  sudo: True

  vars:
    git_user: pp
    git_pass: 1qaz1qaz
    app_name: api_consumer
    repo_url: "https://{{ git_user }}:{{ git_pass }}@phab.octo.ai/diffusion/APICONSUMER/apiconsumer.git"
    repo_remote: origin
    repo_version: master
    repo_dir_name: "{{ ansible_date_time.epoch }}"
    apps_dir: /home/ubuntu/apps

  tasks:
    - name: Ensuring app dir is present
      action: file dest={{ apps_dir }}/{{ app_name }} state=directory

    - name: Ensure directory for api_consumer
      action: file dest={{ apps_dir }}/{{ app_name }}/src state=directory

    - name: deploy code from repository
      git: repo={{ repo_url }}
        dest={{ apps_dir }}/{{ app_name }}/src/{{ repo_dir_name }}
        remote={{ repo_remote }}
        version={{ repo_version }}
        accept_hostkey=yes
        force=True
      async: 30
      poll: 30


    - name: Symlink gems and config
      file: src={{ apps_dir }}/config/ dest={{ apps_dir }}/gems/octo-core/lib/octocore/config/config state=link force=yes

    - name: Symlink API Consumer and config
      file: src={{ apps_dir }}/config/ dest={{ apps_dir }}/{{ app_name }}/src/{{ repo_dir_name }}/config/config state=link force=yes

    - name: Performing bundle install
      shell: cd {{ apps_dir }}/{{ app_name }}/src/{{ repo_dir_name }}/ && bundle install

    - name: Stopping API Consumer
      shell: cd {{ apps_dir }}/{{ app_name }}/run/ && ruby consumer.rb stop
      ignore_errors: True

    - name: Symlinking deployment to run directory
      file: src={{ apps_dir }}/{{ app_name }}/src/{{ repo_dir_name }}/ dest={{ apps_dir }}/{{ app_name }}/run state=link force=yes

    - name: Starting API Handler
      shell: cd {{ apps_dir }}/{{ app_name }}/run && ruby consumer.rb start

